### ISSUE TITLE
Missing PDF file chen2022rotate.pdf

### ISSUE THREAD

**Issue by jamesscottbrown** [visualinteractivedata/visualinteractivedata.github.io#12]
The file `chen2022rotate.pdf` (for the paper "Rotate or Wrap? Interactive Visualisations of Cyclical Data on Cylindrical or Toroidal Topologies:") is missing.

**Comment by sarah37** [comment]
fixed in [d8dc60e](https://github.com/visualinteractivedata/visualinteractivedata.github.io/commit/d8dc60e08c2a16f678d2ec37c578d355bf59fbea)
